# Generated by Django 5.2 on 2025-04-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.IntegerField()),
                ('date', models.DateField()),
                ('postcode', models.CharField(max_length=10)),
                ('consumption', models.FloatField()),
                ('is_holiday_or_weekend', models.BooleanField()),
                ('saison', models.IntegerField()),
                ('consumption_daily_normalized', models.FloatField()),
            ],
            options={
                'unique_together': {('customer', 'date')},
            },
        ),
    ]
