# Generated by Django 5.2 on 2025-04-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Consumer",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
